export const START_FETCHING_MOVIES = "START_FETCHING_MOVIES";
export const STOP_FETCHING_MOVIES = "STOP_FETCHING_MOVIES";
export const SET_MOVIES = "SET_MOVIES";
export const SET_MOVIE = "SET_MOVIE";
export const SET_SPECIALS = "SET_SPECIALS";
